name: wow
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  cached_network_image:
  rxdart:
  http: ^0.13.1
  dio: ^4.0.0
  url_launcher: ^6.0.3
  image_picker: ^0.7.4
  modal_progress_hud: ^0.1.3

  flutter_linkify: ^5.0.2

  draggable_fab: ^0.1.1
  story_view: ^0.12.8
#  flutter_facebook_login: ^3.0.0
  sqflite: ^2.0.0+3
  path_provider: ^2.0.1
  intl: ^0.17.0

  firebase_auth: ^1.0.3
  google_sign_in: ^5.0.1
  firebase_core: ^1.0.3
  #cloud_firestore: ^1.0.4

#Started Extra Feature
  font_awesome_flutter: ^9.0.0
  share: ^2.0.1
  popup_menu: ^1.0.5



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true

  assets:
    - assets/images/







  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf

    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-SemiBold.ttf

    - family: Oxygen
      fonts:
        - asset: assets/fonts/Oxygen-Regular.ttf
        - asset: assets/fonts/Oxygen-Light.ttf
        - asset: assets/fonts/Oxygen-Bold.ttf


    - family: NerkoOne
      fonts:
        - asset: assets/fonts/NerkoOne-Regular.ttf


